GET http://localhost:3000/

###

GET http://localhost:3000/users/

###

GET http://localhost:3000/users/sessions

###

POST http://localhost:3000/users/sign-up
content-type: application/json

{
    "username": "jhon",
    "password": "password123"
}

###

POST http://localhost:3000/users/log-in
content-type: application/json

{
    "username": "jhon",
    "password": "password123"
}

###

POST http://localhost:3000/users/log-out

###

GET http://localhost:3000/users/is-authenticated

###

GET http://localhost:3000/users/is-logged-in

###

DELETE http://localhost:3000/users/